import { describe, expect, it } from "vitest";

import {
  buildExpoMotivationScreenStyleSnapshot,
  buildExpoPlanEditorScreenStyleSnapshot,
  buildExpoReflectionScreenStyleSnapshot,
  buildExpoTodayScreenStyleSnapshot
} from "../apps/expo/src/app-shell/expo-theme-screen-snapshots";
import type { ExpoThemeKey } from "../apps/expo/src/app-shell/expo-theme-presets";

function snapshotRouteScreens(themeKey: ExpoThemeKey) {
  return {
    editor: buildExpoPlanEditorScreenStyleSnapshot(themeKey),
    motivation: buildExpoMotivationScreenStyleSnapshot(themeKey),
    reflection: buildExpoReflectionScreenStyleSnapshot(themeKey),
    today: buildExpoTodayScreenStyleSnapshot(themeKey)
  };
}

describe("expo theme route screen style snapshots", () => {
  it("keeps the sand route style contract stable", () => {
    expect(snapshotRouteScreens("sand")).toMatchInlineSnapshot(`
      {
        "editor": {
          "bottomSheetCard": {
            "backgroundColor": "#fffdf9",
            "borderTopLeftRadius": 28,
            "borderTopRightRadius": 28,
            "gap": 14,
            "maxHeight": "72%",
            "paddingBottom": 28,
            "paddingHorizontal": 18,
            "paddingTop": 18,
          },
          "errorBanner": {
            "backgroundColor": "#fff1ee",
            "borderColor": "#f0c4bc",
            "borderRadius": 16,
            "borderWidth": 1,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "fieldErrorText": {
            "color": "#bc4f43",
            "fontSize": 13,
            "fontWeight": "600",
            "lineHeight": 20,
          },
          "input": {
            "backgroundColor": "#ffffff",
            "borderColor": "#e6ddd6",
            "borderRadius": 16,
            "borderWidth": 1,
            "color": "#22252c",
            "fontSize": 15,
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "inputError": {
            "backgroundColor": "#ffffff",
            "borderColor": "#8f4f43",
            "borderRadius": 16,
            "borderWidth": 1.5,
            "color": "#22252c",
            "fontSize": 15,
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "pickerOptionActive": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#f07c61",
              "borderRadius": 14,
              "justifyContent": "center",
              "minHeight": 44,
              "paddingHorizontal": 12,
            },
            "text": {
              "color": "#ffffff",
              "fontSize": 15,
              "fontWeight": "700",
            },
          },
          "primaryButton": {
            "alignItems": "center",
            "backgroundColor": "#ea765a",
            "borderRadius": 16,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "primaryButtonText": {
            "color": "#ffffff",
            "fontSize": 14,
            "fontWeight": "800",
          },
          "secondaryButton": {
            "alignItems": "center",
            "backgroundColor": "#ffffff",
            "borderColor": "#e6ddd6",
            "borderRadius": 16,
            "borderWidth": 1,
            "flex": 1,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "secondaryButtonText": {
            "color": "#676b78",
            "fontSize": 14,
            "fontWeight": "700",
          },
          "selectOptionsPanel": {
            "backgroundColor": "#fffdf9",
            "borderColor": "#e6ddd6",
            "borderRadius": 16,
            "borderWidth": 1,
            "elevation": 8,
            "gap": 8,
            "left": 0,
            "maxHeight": 220,
            "padding": 8,
            "position": "absolute",
            "right": 0,
            "shadowColor": "#8d7c68",
            "shadowOffset": {
              "height": 10,
              "width": 0,
            },
            "shadowOpacity": 0.12,
            "shadowRadius": 18,
            "top": 56,
            "zIndex": 20,
          },
          "selectRowActive": {
            "alignItems": "center",
            "backgroundColor": "#fff5ef",
            "borderRadius": 14,
            "flexDirection": "row",
            "gap": 10,
            "paddingHorizontal": 12,
            "paddingVertical": 10,
          },
          "selectTrigger": {
            "alignItems": "center",
            "backgroundColor": "#ffffff",
            "borderColor": "#e6ddd6",
            "borderRadius": 16,
            "borderWidth": 1,
            "flexDirection": "row",
            "justifyContent": "space-between",
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "surfaceCard": {
            "backgroundColor": "#fffdf9",
            "borderRadius": 24,
            "gap": 10,
            "padding": 18,
          },
          "timePickerColumn": {
            "backgroundColor": "#f8f5ef",
            "borderRadius": 18,
            "flex": 1,
            "maxHeight": 280,
          },
          "timePreviewCard": {
            "backgroundColor": "#fff5ef",
            "borderRadius": 16,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "warningCard": {
            "backgroundColor": "#fff5ef",
            "borderColor": "#f0d4c4",
            "borderRadius": 16,
            "borderWidth": 1,
            "gap": 6,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
        },
        "motivation": {
          "calendarGood": {
            "container": {
              "backgroundColor": "#e4f4e7",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#2f7b46",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "calendarMid": {
            "container": {
              "backgroundColor": "#fff1dd",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#a06b16",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "calendarWatch": {
            "container": {
              "backgroundColor": "#fde7e4",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#b14a3e",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "legendSwatch": {
            "borderRadius": 999,
            "height": 10,
            "width": 10,
          },
          "metricCard": {
            "backgroundColor": "#fff5ef",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "metricValue": {
            "color": "#22252c",
            "fontSize": 24,
            "fontWeight": "900",
            "letterSpacing": -0.6,
          },
          "plannerCard": {
            "backgroundColor": "#fffdf9",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#8d7c68",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.08,
            "shadowRadius": 24,
          },
          "routeSectionCard": {
            "backgroundColor": "#fffdf9",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#8d7c68",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.06,
            "shadowRadius": 22,
          },
          "statTile": {
            "backgroundColor": "#fff5ef",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "summaryChip": {
            "alignItems": "center",
            "backgroundColor": "rgba(255,255,255,0.76)",
            "borderRadius": 999,
            "flexDirection": "row",
            "gap": 8,
            "paddingHorizontal": 12,
            "paddingVertical": 8,
          },
          "summaryChipValue": {
            "color": "#22252c",
            "fontSize": 13,
            "fontWeight": "800",
          },
          "todayHeadline": {
            "color": "#20242d",
            "fontSize": 22,
            "fontWeight": "900",
            "letterSpacing": -0.5,
          },
        },
        "reflection": {
          "primaryButton": {
            "alignItems": "center",
            "backgroundColor": "#ea765a",
            "borderRadius": 16,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "reflectionTargetCard": {
            "backgroundColor": "#fff5ef",
            "borderRadius": 18,
            "gap": 6,
            "padding": 14,
          },
          "reflectionTargetLabel": {
            "color": "#8a5a4f",
            "fontSize": 12,
            "fontWeight": "800",
            "letterSpacing": 0.3,
            "textTransform": "uppercase",
          },
          "reflectionTargetTitle": {
            "color": "#22252c",
            "fontSize": 19,
            "fontWeight": "800",
            "letterSpacing": -0.4,
          },
          "reflectionTextarea": {
            "backgroundColor": "#ffffff",
            "borderColor": "#e6ddd6",
            "borderRadius": 18,
            "borderWidth": 1,
            "color": "#22252c",
            "fontSize": 15,
            "lineHeight": 22,
            "minHeight": 180,
            "paddingHorizontal": 14,
            "paddingVertical": 14,
          },
          "routeSectionCard": {
            "backgroundColor": "#fffdf9",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#8d7c68",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.06,
            "shadowRadius": 22,
          },
          "secondaryButton": {
            "alignItems": "center",
            "backgroundColor": "#ffffff",
            "borderColor": "#e6ddd6",
            "borderRadius": 16,
            "borderWidth": 1,
            "flex": 1,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "todaySubtitle": {
            "color": "#747884",
            "fontSize": 16,
            "lineHeight": 24,
          },
          "todayTitle": {
            "color": "#20242d",
            "fontSize": 34,
            "fontWeight": "900",
            "letterSpacing": -0.8,
          },
        },
        "today": {
          "errorBanner": {
            "backgroundColor": "#fff1ee",
            "borderColor": "#f0c4bc",
            "borderRadius": 16,
            "borderWidth": 1,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "plannerCard": {
            "backgroundColor": "#fffdf9",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#8d7c68",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.08,
            "shadowRadius": 24,
          },
          "plannerMetaText": {
            "color": "#8c877d",
            "fontSize": 13,
            "fontWeight": "700",
            "lineHeight": 20,
          },
          "routeSafeArea": {
            "backgroundColor": "#f5f2eb",
            "flex": 1,
          },
          "settingsButton": {
            "alignItems": "center",
            "backgroundColor": "#fffdf9",
            "borderColor": "#e6ddd6",
            "borderRadius": 16,
            "borderWidth": 1,
            "height": 42,
            "justifyContent": "center",
            "width": 42,
          },
          "settingsMenu": {
            "backgroundColor": "#fffdf9",
            "borderColor": "#e6ddd6",
            "borderRadius": 16,
            "borderWidth": 1,
            "elevation": 8,
            "position": "absolute",
            "right": 0,
            "shadowColor": "#8d7c68",
            "shadowOffset": {
              "height": 10,
              "width": 0,
            },
            "shadowOpacity": 0.12,
            "shadowRadius": 18,
            "top": 48,
            "width": 180,
            "zIndex": 20,
          },
          "settingsMenuItemActive": {
            "backgroundColor": "#fff5ef",
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "settingsMenuText": {
            "color": "#22252c",
            "fontSize": 14,
            "fontWeight": "700",
          },
          "statTile": {
            "backgroundColor": "#fff5ef",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "statusCurrent": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#fff5ef",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#8f4f43",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusDone": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#e4f4e7",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#2f7b46",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusMissed": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#fde7e4",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#b14a3e",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusPending": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#edf2fb",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#48617f",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "todayHeadline": {
            "color": "#20242d",
            "fontSize": 22,
            "fontWeight": "900",
            "letterSpacing": -0.5,
          },
          "todaySubtitle": {
            "color": "#747884",
            "fontSize": 16,
            "lineHeight": 24,
          },
          "todayTitle": {
            "color": "#20242d",
            "fontSize": 34,
            "fontWeight": "900",
            "letterSpacing": -0.8,
          },
        },
      }
    `);
  });

  it("keeps the mint route style contract stable", () => {
    expect(snapshotRouteScreens("mint")).toMatchInlineSnapshot(`
      {
        "editor": {
          "bottomSheetCard": {
            "backgroundColor": "#fcfffe",
            "borderTopLeftRadius": 28,
            "borderTopRightRadius": 28,
            "gap": 14,
            "maxHeight": "72%",
            "paddingBottom": 28,
            "paddingHorizontal": 18,
            "paddingTop": 18,
          },
          "errorBanner": {
            "backgroundColor": "#fff1ed",
            "borderColor": "#efc4b6",
            "borderRadius": 16,
            "borderWidth": 1,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "fieldErrorText": {
            "color": "#b04c40",
            "fontSize": 13,
            "fontWeight": "600",
            "lineHeight": 20,
          },
          "input": {
            "backgroundColor": "#ffffff",
            "borderColor": "#d4ebe5",
            "borderRadius": 16,
            "borderWidth": 1,
            "color": "#1b2a28",
            "fontSize": 15,
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "inputError": {
            "backgroundColor": "#ffffff",
            "borderColor": "#295d55",
            "borderRadius": 16,
            "borderWidth": 1.5,
            "color": "#1b2a28",
            "fontSize": 15,
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "pickerOptionActive": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#2aa795",
              "borderRadius": 14,
              "justifyContent": "center",
              "minHeight": 44,
              "paddingHorizontal": 12,
            },
            "text": {
              "color": "#ffffff",
              "fontSize": 15,
              "fontWeight": "700",
            },
          },
          "primaryButton": {
            "alignItems": "center",
            "backgroundColor": "#2f9d8f",
            "borderRadius": 16,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "primaryButtonText": {
            "color": "#ffffff",
            "fontSize": 14,
            "fontWeight": "800",
          },
          "secondaryButton": {
            "alignItems": "center",
            "backgroundColor": "#ffffff",
            "borderColor": "#d4ebe5",
            "borderRadius": 16,
            "borderWidth": 1,
            "flex": 1,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "secondaryButtonText": {
            "color": "#5f726d",
            "fontSize": 14,
            "fontWeight": "700",
          },
          "selectOptionsPanel": {
            "backgroundColor": "#fcfffe",
            "borderColor": "#d7ece6",
            "borderRadius": 16,
            "borderWidth": 1,
            "elevation": 8,
            "gap": 8,
            "left": 0,
            "maxHeight": 220,
            "padding": 8,
            "position": "absolute",
            "right": 0,
            "shadowColor": "#6ca399",
            "shadowOffset": {
              "height": 10,
              "width": 0,
            },
            "shadowOpacity": 0.12,
            "shadowRadius": 18,
            "top": 56,
            "zIndex": 20,
          },
          "selectRowActive": {
            "alignItems": "center",
            "backgroundColor": "#eefaf7",
            "borderRadius": 14,
            "flexDirection": "row",
            "gap": 10,
            "paddingHorizontal": 12,
            "paddingVertical": 10,
          },
          "selectTrigger": {
            "alignItems": "center",
            "backgroundColor": "#ffffff",
            "borderColor": "#d4ebe5",
            "borderRadius": 16,
            "borderWidth": 1,
            "flexDirection": "row",
            "justifyContent": "space-between",
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "surfaceCard": {
            "backgroundColor": "#fcfffe",
            "borderRadius": 24,
            "gap": 10,
            "padding": 18,
          },
          "timePickerColumn": {
            "backgroundColor": "#f6fbfa",
            "borderRadius": 18,
            "flex": 1,
            "maxHeight": 280,
          },
          "timePreviewCard": {
            "backgroundColor": "#eefaf7",
            "borderRadius": 16,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "warningCard": {
            "backgroundColor": "#edf9f4",
            "borderColor": "#cde9df",
            "borderRadius": 16,
            "borderWidth": 1,
            "gap": 6,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
        },
        "motivation": {
          "calendarGood": {
            "container": {
              "backgroundColor": "#dff5ed",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#247358",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "calendarMid": {
            "container": {
              "backgroundColor": "#f4f7d8",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#7a7e22",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "calendarWatch": {
            "container": {
              "backgroundColor": "#fde9e2",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#b35741",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "legendSwatch": {
            "borderRadius": 999,
            "height": 10,
            "width": 10,
          },
          "metricCard": {
            "backgroundColor": "#eefaf7",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "metricValue": {
            "color": "#1b2a28",
            "fontSize": 24,
            "fontWeight": "900",
            "letterSpacing": -0.6,
          },
          "plannerCard": {
            "backgroundColor": "#fcfffe",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#6ca399",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.08,
            "shadowRadius": 24,
          },
          "routeSectionCard": {
            "backgroundColor": "#fcfffe",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#6ca399",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.06,
            "shadowRadius": 22,
          },
          "statTile": {
            "backgroundColor": "#eefaf7",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "summaryChip": {
            "alignItems": "center",
            "backgroundColor": "rgba(255,255,255,0.82)",
            "borderRadius": 999,
            "flexDirection": "row",
            "gap": 8,
            "paddingHorizontal": 12,
            "paddingVertical": 8,
          },
          "summaryChipValue": {
            "color": "#1b2a28",
            "fontSize": 13,
            "fontWeight": "800",
          },
          "todayHeadline": {
            "color": "#1b2a28",
            "fontSize": 22,
            "fontWeight": "900",
            "letterSpacing": -0.5,
          },
        },
        "reflection": {
          "primaryButton": {
            "alignItems": "center",
            "backgroundColor": "#2f9d8f",
            "borderRadius": 16,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "reflectionTargetCard": {
            "backgroundColor": "#eefaf7",
            "borderRadius": 18,
            "gap": 6,
            "padding": 14,
          },
          "reflectionTargetLabel": {
            "color": "#467268",
            "fontSize": 12,
            "fontWeight": "800",
            "letterSpacing": 0.3,
            "textTransform": "uppercase",
          },
          "reflectionTargetTitle": {
            "color": "#1b2a28",
            "fontSize": 19,
            "fontWeight": "800",
            "letterSpacing": -0.4,
          },
          "reflectionTextarea": {
            "backgroundColor": "#ffffff",
            "borderColor": "#d4ebe5",
            "borderRadius": 18,
            "borderWidth": 1,
            "color": "#1b2a28",
            "fontSize": 15,
            "lineHeight": 22,
            "minHeight": 180,
            "paddingHorizontal": 14,
            "paddingVertical": 14,
          },
          "routeSectionCard": {
            "backgroundColor": "#fcfffe",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#6ca399",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.06,
            "shadowRadius": 22,
          },
          "secondaryButton": {
            "alignItems": "center",
            "backgroundColor": "#ffffff",
            "borderColor": "#d4ebe5",
            "borderRadius": 16,
            "borderWidth": 1,
            "flex": 1,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "todaySubtitle": {
            "color": "#60706d",
            "fontSize": 16,
            "lineHeight": 24,
          },
          "todayTitle": {
            "color": "#1b2a28",
            "fontSize": 34,
            "fontWeight": "900",
            "letterSpacing": -0.8,
          },
        },
        "today": {
          "errorBanner": {
            "backgroundColor": "#fff1ed",
            "borderColor": "#efc4b6",
            "borderRadius": 16,
            "borderWidth": 1,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "plannerCard": {
            "backgroundColor": "#fcfffe",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#6ca399",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.08,
            "shadowRadius": 24,
          },
          "plannerMetaText": {
            "color": "#5f7b73",
            "fontSize": 13,
            "fontWeight": "700",
            "lineHeight": 20,
          },
          "routeSafeArea": {
            "backgroundColor": "#eef7f4",
            "flex": 1,
          },
          "settingsButton": {
            "alignItems": "center",
            "backgroundColor": "#fcfffe",
            "borderColor": "#d7ece6",
            "borderRadius": 16,
            "borderWidth": 1,
            "height": 42,
            "justifyContent": "center",
            "width": 42,
          },
          "settingsMenu": {
            "backgroundColor": "#fcfffe",
            "borderColor": "#d7ece6",
            "borderRadius": 16,
            "borderWidth": 1,
            "elevation": 8,
            "position": "absolute",
            "right": 0,
            "shadowColor": "#6ca399",
            "shadowOffset": {
              "height": 10,
              "width": 0,
            },
            "shadowOpacity": 0.12,
            "shadowRadius": 18,
            "top": 48,
            "width": 180,
            "zIndex": 20,
          },
          "settingsMenuItemActive": {
            "backgroundColor": "#eefaf7",
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "settingsMenuText": {
            "color": "#1b2a28",
            "fontSize": 14,
            "fontWeight": "700",
          },
          "statTile": {
            "backgroundColor": "#eefaf7",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "statusCurrent": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#eefaf7",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#295d55",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusDone": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#dff5ed",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#247358",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusMissed": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#fde9e2",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#b35741",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusPending": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#e1f5f0",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#31766d",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "todayHeadline": {
            "color": "#1b2a28",
            "fontSize": 22,
            "fontWeight": "900",
            "letterSpacing": -0.5,
          },
          "todaySubtitle": {
            "color": "#60706d",
            "fontSize": 16,
            "lineHeight": 24,
          },
          "todayTitle": {
            "color": "#1b2a28",
            "fontSize": 34,
            "fontWeight": "900",
            "letterSpacing": -0.8,
          },
        },
      }
    `);
  });

  it("keeps the night-ink route style contract stable", () => {
    expect(snapshotRouteScreens("night-ink")).toMatchInlineSnapshot(`
      {
        "editor": {
          "bottomSheetCard": {
            "backgroundColor": "#121827",
            "borderTopLeftRadius": 28,
            "borderTopRightRadius": 28,
            "gap": 14,
            "maxHeight": "72%",
            "paddingBottom": 28,
            "paddingHorizontal": 18,
            "paddingTop": 18,
          },
          "errorBanner": {
            "backgroundColor": "#26141a",
            "borderColor": "#55313a",
            "borderRadius": 16,
            "borderWidth": 1,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "fieldErrorText": {
            "color": "#ffb1b8",
            "fontSize": 13,
            "fontWeight": "600",
            "lineHeight": 20,
          },
          "input": {
            "backgroundColor": "#161d2d",
            "borderColor": "#2f3a56",
            "borderRadius": 16,
            "borderWidth": 1,
            "color": "#f2f5ff",
            "fontSize": 15,
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "inputError": {
            "backgroundColor": "#161d2d",
            "borderColor": "#f0f4ff",
            "borderRadius": 16,
            "borderWidth": 1.5,
            "color": "#f2f5ff",
            "fontSize": 15,
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "pickerOptionActive": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#8ea0ff",
              "borderRadius": 14,
              "justifyContent": "center",
              "minHeight": 44,
              "paddingHorizontal": 12,
            },
            "text": {
              "color": "#09101f",
              "fontSize": 15,
              "fontWeight": "700",
            },
          },
          "primaryButton": {
            "alignItems": "center",
            "backgroundColor": "#7c91ff",
            "borderRadius": 16,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "primaryButtonText": {
            "color": "#09101f",
            "fontSize": 14,
            "fontWeight": "800",
          },
          "secondaryButton": {
            "alignItems": "center",
            "backgroundColor": "#161d2d",
            "borderColor": "#2f3a56",
            "borderRadius": 16,
            "borderWidth": 1,
            "flex": 1,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "secondaryButtonText": {
            "color": "#a7b3d1",
            "fontSize": 14,
            "fontWeight": "700",
          },
          "selectOptionsPanel": {
            "backgroundColor": "#121827",
            "borderColor": "#2e3957",
            "borderRadius": 16,
            "borderWidth": 1,
            "elevation": 8,
            "gap": 8,
            "left": 0,
            "maxHeight": 220,
            "padding": 8,
            "position": "absolute",
            "right": 0,
            "shadowColor": "#02050e",
            "shadowOffset": {
              "height": 10,
              "width": 0,
            },
            "shadowOpacity": 0.12,
            "shadowRadius": 18,
            "top": 56,
            "zIndex": 20,
          },
          "selectRowActive": {
            "alignItems": "center",
            "backgroundColor": "#1b2337",
            "borderRadius": 14,
            "flexDirection": "row",
            "gap": 10,
            "paddingHorizontal": 12,
            "paddingVertical": 10,
          },
          "selectTrigger": {
            "alignItems": "center",
            "backgroundColor": "#161d2d",
            "borderColor": "#2f3a56",
            "borderRadius": 16,
            "borderWidth": 1,
            "flexDirection": "row",
            "justifyContent": "space-between",
            "minHeight": 48,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "surfaceCard": {
            "backgroundColor": "#121827",
            "borderRadius": 24,
            "gap": 10,
            "padding": 18,
          },
          "timePickerColumn": {
            "backgroundColor": "#141c2d",
            "borderRadius": 18,
            "flex": 1,
            "maxHeight": 280,
          },
          "timePreviewCard": {
            "backgroundColor": "#1b2337",
            "borderRadius": 16,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "warningCard": {
            "backgroundColor": "#1b2337",
            "borderColor": "#33415e",
            "borderRadius": 16,
            "borderWidth": 1,
            "gap": 6,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
        },
        "motivation": {
          "calendarGood": {
            "container": {
              "backgroundColor": "#173125",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#91e2b1",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "calendarMid": {
            "container": {
              "backgroundColor": "#372f17",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#f2d780",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "calendarWatch": {
            "container": {
              "backgroundColor": "#371d22",
              "borderRadius": 16,
              "minHeight": 74,
              "paddingHorizontal": 12,
              "paddingVertical": 10,
              "width": "22%",
            },
            "text": {
              "color": "#ff9ca4",
              "fontSize": 13,
              "fontWeight": "800",
            },
          },
          "legendSwatch": {
            "borderRadius": 999,
            "height": 10,
            "width": 10,
          },
          "metricCard": {
            "backgroundColor": "#1b2337",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "metricValue": {
            "color": "#eef2ff",
            "fontSize": 24,
            "fontWeight": "900",
            "letterSpacing": -0.6,
          },
          "plannerCard": {
            "backgroundColor": "#121827",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#02050e",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.08,
            "shadowRadius": 24,
          },
          "routeSectionCard": {
            "backgroundColor": "#121827",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#02050e",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.06,
            "shadowRadius": 22,
          },
          "statTile": {
            "backgroundColor": "#1b2337",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "summaryChip": {
            "alignItems": "center",
            "backgroundColor": "rgba(255,255,255,0.08)",
            "borderRadius": 999,
            "flexDirection": "row",
            "gap": 8,
            "paddingHorizontal": 12,
            "paddingVertical": 8,
          },
          "summaryChipValue": {
            "color": "#eef2ff",
            "fontSize": 13,
            "fontWeight": "800",
          },
          "todayHeadline": {
            "color": "#f3f6ff",
            "fontSize": 22,
            "fontWeight": "900",
            "letterSpacing": -0.5,
          },
        },
        "reflection": {
          "primaryButton": {
            "alignItems": "center",
            "backgroundColor": "#7c91ff",
            "borderRadius": 16,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "reflectionTargetCard": {
            "backgroundColor": "#1b2337",
            "borderRadius": 18,
            "gap": 6,
            "padding": 14,
          },
          "reflectionTargetLabel": {
            "color": "#c3ceee",
            "fontSize": 12,
            "fontWeight": "800",
            "letterSpacing": 0.3,
            "textTransform": "uppercase",
          },
          "reflectionTargetTitle": {
            "color": "#eef2ff",
            "fontSize": 19,
            "fontWeight": "800",
            "letterSpacing": -0.4,
          },
          "reflectionTextarea": {
            "backgroundColor": "#161d2d",
            "borderColor": "#2f3a56",
            "borderRadius": 18,
            "borderWidth": 1,
            "color": "#f2f5ff",
            "fontSize": 15,
            "lineHeight": 22,
            "minHeight": 180,
            "paddingHorizontal": 14,
            "paddingVertical": 14,
          },
          "routeSectionCard": {
            "backgroundColor": "#121827",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#02050e",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.06,
            "shadowRadius": 22,
          },
          "secondaryButton": {
            "alignItems": "center",
            "backgroundColor": "#161d2d",
            "borderColor": "#2f3a56",
            "borderRadius": 16,
            "borderWidth": 1,
            "flex": 1,
            "justifyContent": "center",
            "minHeight": 46,
            "paddingHorizontal": 14,
          },
          "todaySubtitle": {
            "color": "#a7b3d1",
            "fontSize": 16,
            "lineHeight": 24,
          },
          "todayTitle": {
            "color": "#f3f6ff",
            "fontSize": 34,
            "fontWeight": "900",
            "letterSpacing": -0.8,
          },
        },
        "today": {
          "errorBanner": {
            "backgroundColor": "#26141a",
            "borderColor": "#55313a",
            "borderRadius": 16,
            "borderWidth": 1,
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "plannerCard": {
            "backgroundColor": "#121827",
            "borderRadius": 28,
            "gap": 14,
            "padding": 18,
            "shadowColor": "#02050e",
            "shadowOffset": {
              "height": 14,
              "width": 0,
            },
            "shadowOpacity": 0.08,
            "shadowRadius": 24,
          },
          "plannerMetaText": {
            "color": "#8e9ab7",
            "fontSize": 13,
            "fontWeight": "700",
            "lineHeight": 20,
          },
          "routeSafeArea": {
            "backgroundColor": "#0d1320",
            "flex": 1,
          },
          "settingsButton": {
            "alignItems": "center",
            "backgroundColor": "#121827",
            "borderColor": "#2e3957",
            "borderRadius": 16,
            "borderWidth": 1,
            "height": 42,
            "justifyContent": "center",
            "width": 42,
          },
          "settingsMenu": {
            "backgroundColor": "#121827",
            "borderColor": "#2e3957",
            "borderRadius": 16,
            "borderWidth": 1,
            "elevation": 8,
            "position": "absolute",
            "right": 0,
            "shadowColor": "#02050e",
            "shadowOffset": {
              "height": 10,
              "width": 0,
            },
            "shadowOpacity": 0.12,
            "shadowRadius": 18,
            "top": 48,
            "width": 180,
            "zIndex": 20,
          },
          "settingsMenuItemActive": {
            "backgroundColor": "#1b2337",
            "paddingHorizontal": 14,
            "paddingVertical": 12,
          },
          "settingsMenuText": {
            "color": "#eef2ff",
            "fontSize": 14,
            "fontWeight": "700",
          },
          "statTile": {
            "backgroundColor": "#1b2337",
            "borderRadius": 18,
            "flex": 1,
            "gap": 6,
            "padding": 14,
          },
          "statusCurrent": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#1b2337",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#f0f4ff",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusDone": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#173125",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#91e2b1",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusMissed": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#371d22",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#ff9ca4",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "statusPending": {
            "container": {
              "alignItems": "center",
              "backgroundColor": "#222c41",
              "borderRadius": 999,
              "justifyContent": "center",
              "minHeight": 28,
              "paddingHorizontal": 10,
            },
            "text": {
              "color": "#dbe3ff",
              "fontSize": 12,
              "fontWeight": "800",
            },
          },
          "todayHeadline": {
            "color": "#f3f6ff",
            "fontSize": 22,
            "fontWeight": "900",
            "letterSpacing": -0.5,
          },
          "todaySubtitle": {
            "color": "#a7b3d1",
            "fontSize": 16,
            "lineHeight": 24,
          },
          "todayTitle": {
            "color": "#f3f6ff",
            "fontSize": 34,
            "fontWeight": "900",
            "letterSpacing": -0.8,
          },
        },
      }
    `);
  });

  it("keeps key screen tones visually separated across themes", () => {
    const sand = snapshotRouteScreens("sand");
    const mint = snapshotRouteScreens("mint");
    const nightInk = snapshotRouteScreens("night-ink");

    expect(sand.editor.primaryButton.backgroundColor).not.toBe(
      mint.editor.primaryButton.backgroundColor
    );
    expect(mint.editor.primaryButton.backgroundColor).not.toBe(
      nightInk.editor.primaryButton.backgroundColor
    );
    expect(sand.reflection.reflectionTextarea.backgroundColor).not.toBe(
      nightInk.reflection.reflectionTextarea.backgroundColor
    );
    expect(sand.motivation.calendarGood.container.backgroundColor).not.toBe(
      sand.motivation.calendarWatch.container.backgroundColor
    );
    expect(mint.motivation.summaryChip.backgroundColor).not.toBe(
      mint.today.plannerCard.backgroundColor
    );
  });
});
